---
services:
  cpro:
    extends:
      file: ../base/docker-compose.yaml
      service: cpro
    env_file:
      - cpro.env
    depends_on:
      - mysql
  mysql:
    extends:
      file: ../base/docker-compose.yaml
      service: mysql

  db:
    extends:
      file: ../base/docker-compose.yaml
      service: db

  keycloak:
    extends:
      file: ../base/docker-compose.yaml
      service: keycloak
    env_file:
      - keycloak.env
    depends_on:
      - db

volumes:
  mysql-data: {}
  secure-data: {}
  db-data: {}
  tmp-data: {}
networks:
  # internal network for backing services
  internal:

  # ingress network
  ingress:
    external: true
    name: external_web
